Thu Nov  3 00:40:31 2022 - INFO  - Start to prepare the test environment.
Failed to enable unit: Unit file pmcd.service does not exist.
Failed to start pmcd.service: Unit pmcd.service not found.
Failed to enable unit: Unit file pmlogger.service does not exist.
Failed to start pmlogger.service: Unit pmlogger.service not found.
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行24: pcp：未找到命令
Thu Nov  3 00:42:36 2022 - INFO  - End to prepare the test environment.
Thu Nov  3 00:42:39 2022 - INFO  - Start to run test.
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行47: pmfind：未找到命令
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行49: pmgenmap：未找到命令
Thu Nov  3 00:42:41 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 50
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行51: pmie2col：未找到命令
timeout: 无法运行命令 “pmie”: No such file or directory
Thu Nov  3 00:42:43 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 52
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行53: pminfo：未找到命令
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行55: pminfo：未找到命令
Thu Nov  3 00:42:46 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 56
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行57: pminfo：未找到命令
Thu Nov  3 00:42:49 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 58
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行59: pminfo：未找到命令
Thu Nov  3 00:42:51 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 60
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行61: pminfo：未找到命令
Thu Nov  3 00:42:54 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 62
oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh:行63: pminfo：未找到命令
Thu Nov  3 00:42:56 2022 - ERROR - oe_test_pmfind_pmgenmap_pmie2col_pminfo_01.sh line 64
Thu Nov  3 00:42:58 2022 - INFO  - End to run test.
Thu Nov  3 00:43:00 2022 - ERROR - failed to execute the case.
Thu Nov  3 00:43:03 2022 - INFO  - Start to restore the test environment.
Traceback (most recent call last):
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 0:28:57 ago on 2022年11月03日 星期四 00时13分08秒.\nNo match for argument: pcp\nError: Unable to find a match: pcp'
Thu Nov  3 00:43:15 2022 - INFO  - End to restore the test environment.
