+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Nov 11 21:31:04 2022 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'freeradius freeradius-utils'
+ pkgs='freeradius freeradius-utils'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'freeradius freeradius-utils' --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 0:00:49 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 0:00:49 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Nov 11 21:31:48 2022 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Nov 11 21:31:49 2022 - INFO  - Start to run test.
+ radzap -h
+ grep Usage
+ CHECK_RESULT 1 0 0 'radzap -h execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -h execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -h execution failed.'
+ LOG_ERROR 'radzap -h execution failed.'
+ message='radzap -h execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -h execution failed.'
Fri Nov 11 21:31:50 2022 - ERROR - radzap -h execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 33'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 33'
Fri Nov 11 21:31:51 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 33
+ return 0
+ systemctl start radiusd
Failed to start radiusd.service: Unit radiusd.service not found.
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ radzap -d /etc/raddb/ -N 127.0.0.1 127.0.0.1 testing123
+ grep Accounting-Response
oe_test_freeradius_freeradius-utils_radzap.sh: line 36: radzap: command not found
+ CHECK_RESULT 1 0 0 'radzap -d -N execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -d -N execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -d -N execution failed.'
+ LOG_ERROR 'radzap -d -N execution failed.'
+ message='radzap -d -N execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -d -N execution failed.'
Fri Nov 11 21:31:55 2022 - ERROR - radzap -d -N execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 37'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 37'
Fri Nov 11 21:31:56 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 37
+ return 0
+ radzap -D /usr/share/freeradius -N 127.0.0.1 127.0.0.1 testing123
+ grep Accounting-Response
oe_test_freeradius_freeradius-utils_radzap.sh: line 38: radzap: command not found
+ CHECK_RESULT 1 0 0 'radzap -D -N execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -D -N execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -D -N execution failed.'
+ LOG_ERROR 'radzap -D -N execution failed.'
+ message='radzap -D -N execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -D -N execution failed.'
Fri Nov 11 21:31:58 2022 - ERROR - radzap -D -N execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 39'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 39'
Fri Nov 11 21:31:59 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 39
+ return 0
+ touch /var/log/radius/radutmp
touch: cannot touch '/var/log/radius/radutmp': No such file or directory
+ '[' -e /var/log/radius/radutmp ']'
+ CHECK_RESULT 1 0 0 'touch radutmp failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='touch radutmp failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'touch radutmp failed.'
+ LOG_ERROR 'touch radutmp failed.'
+ message='touch radutmp failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'touch radutmp failed.'
Fri Nov 11 21:32:00 2022 - ERROR - touch radutmp failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 42'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 42'
Fri Nov 11 21:32:01 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 42
+ return 0
+ radzap -P 0 127.0.0.1 testing123
+ grep send
+ CHECK_RESULT 1 0 0 'radzap -P execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -P execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -P execution failed.'
+ LOG_ERROR 'radzap -P execution failed.'
+ message='radzap -P execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -P execution failed.'
Fri Nov 11 21:32:02 2022 - ERROR - radzap -P execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 44'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 44'
Fri Nov 11 21:32:03 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 44
+ return 0
+ radzap -u steve 127.0.0.1 testing123
+ grep send
+ CHECK_RESULT 1 0 0 'radzap -u execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -u execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -u execution failed.'
+ LOG_ERROR 'radzap -u execution failed.'
+ message='radzap -u execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -u execution failed.'
Fri Nov 11 21:32:04 2022 - ERROR - radzap -u execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 46'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 46'
Fri Nov 11 21:32:05 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 46
+ return 0
+ radzap -U steve 127.0.0.1 testing123
+ grep send
+ CHECK_RESULT 1 0 0 'radzap -U execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -U execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -U execution failed.'
+ LOG_ERROR 'radzap -U execution failed.'
+ message='radzap -U execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -U execution failed.'
Fri Nov 11 21:32:06 2022 - ERROR - radzap -U execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 48'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 48'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 48'
Fri Nov 11 21:32:07 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 48
+ return 0
+ radzap -x -N 127.0.0.1 127.0.0.1 testing123
oe_test_freeradius_freeradius-utils_radzap.sh: line 49: radzap: command not found
+ grep NAS-IP-Address
+ CHECK_RESULT 1 0 0 'radzap -x -N execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radzap -x -N execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radzap -x -N execution failed.'
+ LOG_ERROR 'radzap -x -N execution failed.'
+ message='radzap -x -N execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radzap -x -N execution failed.'
Fri Nov 11 21:32:08 2022 - ERROR - radzap -x -N execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radzap.sh line 50'
+ message='oe_test_freeradius_freeradius-utils_radzap.sh line 50'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radzap.sh line 50'
Fri Nov 11 21:32:09 2022 - ERROR - oe_test_freeradius_freeradius-utils_radzap.sh line 50
+ return 0
+ systemctl stop radiusd
Failed to stop radiusd.service: Unit radiusd.service not loaded.
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Nov 11 21:32:11 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Nov 11 21:32:12 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Nov 11 21:32:13 2022 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 0:00:49 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 0:00:49 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:00:49 ago on Fri 11 Nov 2022 09:30:56 PM CST.\nError: \n Problem: conflicting requests\n  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ rm -rf /etc/raddb
+ rm -rf /var/log/radius
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Nov 11 21:32:18 2022 - INFO  - End to restore the test environment.
