+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Nov 11 22:06:56 2022 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'freeradius freeradius-utils'
+ pkgs='freeradius freeradius-utils'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'freeradius freeradius-utils' --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 0:36:34 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 0:36:34 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ systemctl start radiusd
Failed to start radiusd.service: Unit radiusd.service not found.
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Nov 11 22:07:34 2022 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Nov 11 22:07:35 2022 - INFO  - Start to run test.
+ echo 'Message-Authenticator = 0x00'
+ radclient -p 30 127.0.0.1 status testing123
+ grep 'Received Access-Accept'
oe_test_freeradius_freeradius-utils_radclient2.sh: line 34: radclient: command not found
+ CHECK_RESULT 1 0 0 'radclient -p execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -p execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -p execution failed.'
+ LOG_ERROR 'radclient -p execution failed.'
+ message='radclient -p execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -p execution failed.'
Fri Nov 11 22:07:36 2022 - ERROR - radclient -p execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 35'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 35'
Fri Nov 11 22:07:37 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 35
+ return 0
++ echo 'Message-Authenticator = 0x00'
++ radclient -q 127.0.0.1 status testing123
oe_test_freeradius_freeradius-utils_radclient2.sh: line 36: radclient: command not found
+ a=
+ '[' -z '' ']'
+ CHECK_RESULT 0 0 0 'radclient -q execution failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='radclient -q execution failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radclient -t 0.0000000000000000000000000000000000000000000000000000000001 127.0.0.1 status testing123
+ grep 'No reply'
+ CHECK_RESULT 1 0 0 'radclient -t execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -t execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -t execution failed.'
+ LOG_ERROR 'radclient -t execution failed.'
+ message='radclient -t execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -t execution failed.'
Fri Nov 11 22:07:39 2022 - ERROR - radclient -t execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 40'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 40'
Fri Nov 11 22:07:40 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 40
+ return 0
+ replay_times=5
++ echo 'Message-Authenticator = 0x00'
++ radclient -t 0.0000000000000000000000000000000000000000000000000000000001 -r 5 127.0.0.1 status testing123
++ grep -c Sent
oe_test_freeradius_freeradius-utils_radclient2.sh: line 42: radclient: command not found
+ a=0
+ '[' 5 -eq 0 ']'
+ CHECK_RESULT 1 0 0 'radclient -r execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -r execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -r execution failed.'
+ LOG_ERROR 'radclient -r execution failed.'
+ message='radclient -r execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -r execution failed.'
Fri Nov 11 22:07:41 2022 - ERROR - radclient -r execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 44'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 44'
Fri Nov 11 22:07:42 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 44
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radclient -s 127.0.0.1 status testing123
+ grep 'Packet summary'
oe_test_freeradius_freeradius-utils_radclient2.sh: line 45: radclient: command not found
+ CHECK_RESULT 1 0 0 'radclient -s execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -s execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -s execution failed.'
+ LOG_ERROR 'radclient -s execution failed.'
+ message='radclient -s execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -s execution failed.'
Fri Nov 11 22:07:44 2022 - ERROR - radclient -s execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 46'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 46'
Fri Nov 11 22:07:45 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 46
+ return 0
+ echo testing123
+ echo 'Message-Authenticator = 0x00'
+ radclient -S /tmp/test 127.0.0.1 status
+ grep 'Received Access-Accept'
oe_test_freeradius_freeradius-utils_radclient2.sh: line 48: radclient: command not found
+ CHECK_RESULT 1 0 0 'radclient -S execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -S execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -S execution failed.'
+ LOG_ERROR 'radclient -S execution failed.'
+ message='radclient -S execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -S execution failed.'
Fri Nov 11 22:07:46 2022 - ERROR - radclient -S execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 49'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 49'
Fri Nov 11 22:07:47 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 49
+ return 0
+ radclient -v
oe_test_freeradius_freeradius-utils_radclient2.sh: line 50: radclient: command not found
++ rpm -q freeradius-utils
++ awk -F - '{print $3}'
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2 0 0 'radclient -v execution failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='radclient -v execution failed.'
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'radclient -v execution failed.'
+ LOG_ERROR 'radclient -v execution failed.'
+ message='radclient -v execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -v execution failed.'
Fri Nov 11 22:07:48 2022 - ERROR - radclient -v execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 51'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 51'
Fri Nov 11 22:07:49 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 51
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radclient -x 127.0.0.1 status testing123
oe_test_freeradius_freeradius-utils_radclient2.sh: line 52: radclient: command not found
+ grep Message-Authenticator
+ CHECK_RESULT 1 0 0 'radclient -x execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -x execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -x execution failed.'
+ LOG_ERROR 'radclient -x execution failed.'
+ message='radclient -x execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -x execution failed.'
Fri Nov 11 22:07:50 2022 - ERROR - radclient -x execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 53'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 53'
Fri Nov 11 22:07:51 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 53
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radclient -P udp 127.0.0.1 status testing123
+ grep 'Received Access-Accept'
oe_test_freeradius_freeradius-utils_radclient2.sh: line 54: radclient: command not found
+ CHECK_RESULT 1 0 0 'radclient -P execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radclient -P execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radclient -P execution failed.'
+ LOG_ERROR 'radclient -P execution failed.'
+ message='radclient -P execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radclient -P execution failed.'
Fri Nov 11 22:07:52 2022 - ERROR - radclient -P execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radclient2.sh line 55'
+ message='oe_test_freeradius_freeradius-utils_radclient2.sh line 55'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radclient2.sh line 55'
Fri Nov 11 22:07:53 2022 - ERROR - oe_test_freeradius_freeradius-utils_radclient2.sh line 55
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Nov 11 22:07:54 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Nov 11 22:07:55 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Nov 11 22:07:56 2022 - INFO  - Start to restore the test environment.
+ systemctl stop radiusd
Failed to stop radiusd.service: Unit radiusd.service not loaded.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 0:36:34 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 0:36:34 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:36:34 ago on Fri 11 Nov 2022 09:30:56 PM CST.\nError: \n Problem: conflicting requests\n  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ rm -rf /etc/raddb
+ rm -rf /var/log/radius
+ rm -rf /tmp/test
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Nov 11 22:08:01 2022 - INFO  - End to restore the test environment.
