+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Nov 11 21:46:17 2022 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'freeradius freeradius-utils net-tools'
+ pkgs='freeradius freeradius-utils net-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'freeradius freeradius-utils net-tools' --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 0:15:54 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Package net-tools-2.10-1.oe2203.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 0:15:54 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Package net-tools-2.10-1.oe2203.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ systemctl start radiusd
Failed to start radiusd.service: Unit radiusd.service not found.
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Nov 11 21:46:55 2022 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Nov 11 21:46:56 2022 - INFO  - Start to run test.
+ echo 'Message-Authenticator = 0x00'
+ grep 'Main loop: done'
+ radeapclient -p 30 127.0.0.1 status testing123
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 34: radeapclient: command not found
+ CHECK_RESULT 1 0 0 'radeapclient -p execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -p execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -p execution failed.'
+ LOG_ERROR 'radeapclient -p execution failed.'
+ message='radeapclient -p execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -p execution failed.'
Fri Nov 11 21:46:57 2022 - ERROR - radeapclient -p execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 35'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 35'
Fri Nov 11 21:46:58 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 35
+ return 0
++ echo 'Message-Authenticator = 0x00'
++ radeapclient -q 127.0.0.1 status testing123
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 36: radeapclient: command not found
+ a=
+ '[' -z '' ']'
+ CHECK_RESULT 0 0 0 'radeapclient -q execution failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='radeapclient -q execution failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radeapclient -t 0.0000000000000000000000000000000000000000000000000000000001 -x 127.0.0.1 status testing123
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 39: radeapclient: command not found
+ grep Timeout
+ CHECK_RESULT 1 0 0 'radeapclient -t execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -t execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -t execution failed.'
+ LOG_ERROR 'radeapclient -t execution failed.'
+ message='radeapclient -t execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -t execution failed.'
Fri Nov 11 21:46:59 2022 - ERROR - radeapclient -t execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 40'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 40'
Fri Nov 11 21:47:00 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 40
+ return 0
+ replay_times=5
++ echo 'Message-Authenticator = 0x00'
++ radeapclient -t 0.0000000000000000000000000000000000000000000000000000000001 -r 5 -x 127.0.0.1 status testing123
++ grep -c Timeout
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 42: radeapclient: command not found
+ a=0
+ '[' 5 -eq 0 ']'
+ CHECK_RESULT 1 0 0 'radeapclient -r execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -r execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -r execution failed.'
+ LOG_ERROR 'radeapclient -r execution failed.'
+ message='radeapclient -r execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -r execution failed.'
Fri Nov 11 21:47:01 2022 - ERROR - radeapclient -r execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 44'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 44'
Fri Nov 11 21:47:02 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 44
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radeapclient -s 127.0.0.1 status testing123
+ grep 'Total approved auths'
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 45: radeapclient: command not found
+ CHECK_RESULT 1 0 0 'radeapclient -s execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -s execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -s execution failed.'
+ LOG_ERROR 'radeapclient -s execution failed.'
+ message='radeapclient -s execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -s execution failed.'
Fri Nov 11 21:47:03 2022 - ERROR - radeapclient -s execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 46'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 46'
Fri Nov 11 21:47:04 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 46
+ return 0
+ echo testing123
+ echo 'Message-Authenticator = 0x00'
+ radeapclient -S /tmp/secretfile 127.0.0.1 status
+ grep 'Main loop: done'
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 48: radeapclient: command not found
+ CHECK_RESULT 1 0 0 'radeapclient -S execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -S execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -S execution failed.'
+ LOG_ERROR 'radeapclient -S execution failed.'
+ message='radeapclient -S execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -S execution failed.'
Fri Nov 11 21:47:05 2022 - ERROR - radeapclient -S execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 49'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 49'
Fri Nov 11 21:47:06 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 49
+ return 0
+ radeapclient -v
+ grep -i id
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 50: radeapclient: command not found
+ CHECK_RESULT 1 0 0 'radeapclient -v execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -v execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -v execution failed.'
+ LOG_ERROR 'radeapclient -v execution failed.'
+ message='radeapclient -v execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -v execution failed.'
Fri Nov 11 21:47:08 2022 - ERROR - radeapclient -v execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 51'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 51'
Fri Nov 11 21:47:09 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 51
+ return 0
+ echo 'Message-Authenticator = 0x00'
+ radeapclient -x 127.0.0.1 status testing123
+ grep Message-Authenticator
oe_test_freeradius_freeradius-utils_radeapclient.sh: line 52: radeapclient: command not found
+ CHECK_RESULT 1 0 0 'radeapclient -x execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radeapclient -x execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radeapclient -x execution failed.'
+ LOG_ERROR 'radeapclient -x execution failed.'
+ message='radeapclient -x execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'radeapclient -x execution failed.'
Fri Nov 11 21:47:10 2022 - ERROR - radeapclient -x execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 53'
+ message='oe_test_freeradius_freeradius-utils_radeapclient.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_freeradius_freeradius-utils_radeapclient.sh line 53'
Fri Nov 11 21:47:11 2022 - ERROR - oe_test_freeradius_freeradius-utils_radeapclient.sh line 53
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Nov 11 21:47:12 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Nov 11 21:47:13 2022 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Nov 11 21:47:14 2022 - INFO  - Start to restore the test environment.
+ systemctl stop radiusd
Failed to stop radiusd.service: Unit radiusd.service not loaded.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 0:15:54 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Package net-tools-2.10-1.oe2203.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 0:15:54 ago on Fri 11 Nov 2022 09:30:56 PM CST.
Package net-tools-2.10-1.oe2203.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:15:54 ago on Fri 11 Nov 2022 09:30:56 PM CST.\nPackage net-tools-2.10-1.oe2203.riscv64 is already installed.\nError: \n Problem: conflicting requests\n  - nothing provides perl(Net::IP) needed by freeradius-utils-3.0.25-1.oe2203.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ rm -rf /etc/raddb
+ rm -rf /var/log/radius
+ rm -rf /tmp/secretfile
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Nov 11 21:47:19 2022 - INFO  - End to restore the test environment.
