Thu Nov  3 00:51:51 2022 - INFO  - Start to prepare the test environment.
Failed to enable unit: Unit file pmcd.service does not exist.
Failed to start pmcd.service: Unit pmcd.service not found.
Failed to enable unit: Unit file pmlogger.service does not exist.
Failed to start pmlogger.service: Unit pmlogger.service not found.
oe_test_pmlogconf_pmlogsize.sh:行24: pcp：未找到命令
Thu Nov  3 00:54:09 2022 - INFO  - End to prepare the test environment.
Thu Nov  3 00:54:13 2022 - INFO  - Start to run test.
oe_test_pmlogconf_pmlogsize.sh:行30: pmlogconf：未找到命令
Thu Nov  3 00:54:17 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 31
grep: configfile: No such file or directory
Thu Nov  3 00:54:20 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 33
oe_test_pmlogconf_pmlogsize.sh:行35: pmlogconf：未找到命令
Thu Nov  3 00:54:24 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 36
grep: configfile: No such file or directory
Thu Nov  3 00:54:29 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 38
oe_test_pmlogconf_pmlogsize.sh:行40: pmlogconf：未找到命令
Thu Nov  3 00:54:33 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 41
Thu Nov  3 00:54:36 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 43
oe_test_pmlogconf_pmlogsize.sh:行45: pmlogconf：未找到命令
Thu Nov  3 00:54:40 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 46
Thu Nov  3 00:54:43 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 48
oe_test_pmlogconf_pmlogsize.sh:行50: pmlogsize：未找到命令
Thu Nov  3 00:54:46 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 51
oe_test_pmlogconf_pmlogsize.sh:行52: pmlogsize：未找到命令
Thu Nov  3 00:54:50 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 53
oe_test_pmlogconf_pmlogsize.sh:行54: pmlogsize：未找到命令
Thu Nov  3 00:54:53 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 55
oe_test_pmlogconf_pmlogsize.sh:行56: pmlogsize：未找到命令
Thu Nov  3 00:54:57 2022 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 57
Thu Nov  3 00:55:00 2022 - INFO  - End to run test.
Thu Nov  3 00:55:03 2022 - ERROR - failed to execute the case.
Thu Nov  3 00:55:06 2022 - INFO  - Start to restore the test environment.
Traceback (most recent call last):
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 0:40:22 ago on 2022年11月03日 星期四 00时13分08秒.\nNo match for argument: pcp\nError: Unable to find a match: pcp'
Thu Nov  3 00:55:21 2022 - INFO  - End to restore the test environment.
