+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Nov 17 13:12:00 2022 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'java-1.8.0-openjdk*'
+ pkgs='java-1.8.0-openjdk*'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'java-1.8.0-openjdk*' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp6pm5yb0c
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp6pm5yb0c
+ cp ../common/Hello.java .
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu Nov 17 13:24:43 2022 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Nov 17 13:24:45 2022 - INFO  - Start to run test.
+ jdb -help
+ grep Usage
Usage: jdb <options> <class> <arguments>
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ javac Hello.java
Thu Nov 17 13:41:57 2022 - ERROR - Timeout : Command 'bash -x oe_test_openjdk_jdb_jdeps.sh' timed out after 1799.9985185200003 seconds
++ post_test
++ LOG_INFO 'Need'\''t to restore the tet environment.'
++ message='Need'\''t to restore the tet environment.'
++ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Need'\''t to restore the tet environment.'
Thu Nov 17 13:43:52 2022 - INFO  - Need't to restore the tet environment.
++ DNF_REMOVE
++ node=1
++ pkg_list=
++ mode=0
++ [[ -z /tmp/tmp6pm5yb0c ]]
++ '[' 0 -ne 0 ']'
++ '[' 1 == 0 ']'
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp6pm5yb0c
++ '[' 0 -ne 0 ']'
++ rm -rf Hello.class Hello.java 'testlog*'
++ LOG_INFO 'End to restore the test environment.'
++ message='End to restore the test environment.'
++ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Nov 17 13:45:21 2022 - INFO  - End to restore the test environment.
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ expect -c '
    log_file testlog
    spawn jdb
    expect ">"
    send "help\r"
    expect ">"
    send "run Hello\r"
    expect eof
'
spawn jdb
couldn't execute "jdb": no such file or directory
    while executing
"spawn jdb"
+ grep 'while executing' testlog
    while executing
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 44'
+ message='oe_test_openjdk_jdb_jdeps.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 44'
Thu Nov 17 13:45:24 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 44
+ return 0
+ grep 'command list' testlog
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 46'
+ message='oe_test_openjdk_jdb_jdeps.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 46'
Thu Nov 17 13:45:25 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 46
+ return 0
+ grep 'VM Started' testlog
+ grep 'Hello,world!'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 48'
+ message='oe_test_openjdk_jdb_jdeps.sh line 48'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 48'
Thu Nov 17 13:45:27 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 48
+ return 0
+ jdeps -help
+ grep Usage
oe_test_openjdk_jdb_jdeps.sh: line 50: jdeps: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 51'
+ message='oe_test_openjdk_jdb_jdeps.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 51'
Thu Nov 17 13:45:28 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 51
+ return 0
+ jdeps -version
oe_test_openjdk_jdb_jdeps.sh: line 52: jdeps: command not found
+ grep '[0-9]'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 53'
+ message='oe_test_openjdk_jdb_jdeps.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 53'
Thu Nov 17 13:45:30 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 53
+ return 0
+ jfr help
oe_test_openjdk_jdb_jdeps.sh: line 55: jfr: command not found
+ grep 'jfr print'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 56'
+ message='oe_test_openjdk_jdb_jdeps.sh line 56'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 56'
Thu Nov 17 13:45:32 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 56
+ return 0
+ jfr version
+ grep '[0-9]'
oe_test_openjdk_jdb_jdeps.sh: line 57: jfr: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 58'
+ message='oe_test_openjdk_jdb_jdeps.sh line 58'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 58'
Thu Nov 17 13:45:33 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 58
+ return 0
+ jhat -h
+ grep Usage
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 61'
+ message='oe_test_openjdk_jdb_jdeps.sh line 61'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 61'
Thu Nov 17 13:45:35 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 61
+ return 0
+ jhat -version
oe_test_openjdk_jdb_jdeps.sh: line 62: jhat: command not found
+ grep 'jhat version'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 63'
+ message='oe_test_openjdk_jdb_jdeps.sh line 63'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 63'
Thu Nov 17 13:45:36 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 63
+ return 0
+ jinfo -h
+ grep Usage
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openjdk_jdb_jdeps.sh line 66'
+ message='oe_test_openjdk_jdb_jdeps.sh line 66'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openjdk_jdb_jdeps.sh line 66'
Thu Nov 17 13:45:38 2022 - ERROR - oe_test_openjdk_jdb_jdeps.sh line 66
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Nov 17 13:45:39 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Nov 17 13:45:41 2022 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'Need'\''t to restore the tet environment.'
+ message='Need'\''t to restore the tet environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Need'\''t to restore the tet environment.'
Thu Nov 17 13:45:43 2022 - INFO  - Need't to restore the tet environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp6pm5yb0c ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp6pm5yb0c
+ '[' 0 -ne 0 ']'
+ rm -rf 'Hello.*' testlog
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Nov 17 13:45:58 2022 - INFO  - End to restore the test environment.
